"""
Prototype Demo Dataset — representative sample of title-style records.

IMPORTANT: These are invented demonstration titles for the student prototype.
They are NOT official PRGI records.  The PPT's real-world context refers to
~160,000 registered titles; this dataset is only a small representative slice
showing duplicates, spelling variants, phonetic variants, semantic variants
and multilingual examples.
"""
from __future__ import annotations

# (title, language, category, region)
SEED_TITLES: list[tuple[str, str, str, str]] = [
    # --- required demonstration pairs/triples -------------------------------
    ("Indian Express", "English", "National Daily", "Delhi"),
    ("Indian Xpress", "English", "National Daily", "Mumbai"),
    ("Indian Express Daily", "English", "National Daily", "Delhi"),
    ("Phoenix", "English", "Evening Tabloid", "Pune"),
    ("Foenix", "English", "Lifestyle Weekly", "Goa"),
    ("Daily Evening", "English", "Evening Daily", "Mumbai"),
    ("Pratidin Sandhya", "Hindi", "Evening Daily", "Bhopal"),
    ("Daily Star", "English", "National Daily", "Chennai"),
    ("The Star", "English", "City Daily", "Hyderabad"),
    ("Namaskar", "Hindi", "Morning Daily", "Jaipur"),
    ("Namascar", "Hindi", "Morning Daily", "Indore"),

    # --- English national / metro dailies -----------------------------------
    ("Morning Chronicle", "English", "Morning Daily", "Mumbai"),
    ("The Daily Herald", "English", "National Daily", "Delhi"),
    ("City Voice", "English", "City Daily", "Bengaluru"),
    ("Metro Mirror", "English", "City Daily", "Pune"),
    ("The National Post", "English", "National Daily", "Delhi"),
    ("Business Standard Daily", "English", "Business Daily", "Mumbai"),
    ("Market Pulse", "English", "Business Daily", "Mumbai"),
    ("The Sunday Guardian", "English", "Weekly", "Delhi"),
    ("Weekend Observer", "English", "Weekly", "Chennai"),
    ("The Pioneer Post", "English", "National Daily", "Lucknow"),
    ("Coastal Times", "English", "Regional Daily", "Mangaluru"),
    ("The Eastern Sun", "English", "Regional Daily", "Kolkata"),
    ("Western Mail", "English", "Regional Daily", "Ahmedabad"),
    ("Deccan Chronicle Daily", "English", "Regional Daily", "Hyderabad"),
    ("The Tribune Times", "English", "Regional Daily", "Chandigarh"),
    ("Dawn Herald", "English", "Morning Daily", "Srinagar"),
    ("Twilight Post", "English", "Evening Daily", "Nagpur"),
    ("The Urban Mirror", "English", "City Daily", "Gurugram"),
    ("Capital Voice", "English", "City Daily", "Delhi"),
    ("Harbour News", "English", "City Daily", "Mumbai"),
    ("Golden Age Gazette", "English", "Weekly", "Mysuru"),
    ("The Weekly Standard", "English", "Weekly", "Kochi"),
    ("Education Times Weekly", "English", "Education", "Delhi"),
    ("Sports Arena", "English", "Sports", "Mumbai"),
    ("Health Chronicle", "English", "Health", "Bengaluru"),
    ("Farmer's Friend", "English", "Agriculture", "Nashik"),
    ("Women's Era Weekly", "English", "Lifestyle", "Delhi"),
    ("Youth Junction", "English", "Youth", "Pune"),
    ("Tech Tomorrow", "English", "Technology", "Bengaluru"),
    ("Science Reporter Weekly", "English", "Science", "Delhi"),
    ("Food & Flavours", "English", "Lifestyle", "Mumbai"),
    ("Travel Trails", "English", "Travel", "Goa"),
    ("Property Post", "English", "Real Estate", "Mumbai"),
    ("Auto Express India", "English", "Automotive", "Chennai"),
    ("Cinema Scope", "English", "Entertainment", "Mumbai"),
    ("The Legal Eagle", "English", "Law", "Delhi"),
    ("Election Watch", "English", "Politics", "Delhi"),
    ("Weather Weekly", "English", "Environment", "Pune"),
    ("Green Earth Times", "English", "Environment", "Dehradun"),
    ("The Silver Screen", "English", "Entertainment", "Mumbai"),
    ("Market Mirror", "English", "Business", "Ahmedabad"),
    ("Trade Tribune", "English", "Business", "Surat"),
    ("Startup Chronicle", "English", "Business", "Bengaluru"),
    ("The Campus Post", "English", "Education", "Pune"),
    ("River City News", "English", "City Daily", "Guwahati"),
    ("Desert Sun Daily", "English", "Regional Daily", "Jodhpur"),
    ("Himalayan Voice", "English", "Regional Daily", "Shimla"),
    ("Island Times", "English", "Regional Daily", "Port Blair"),
    ("The Free Press Daily", "English", "City Daily", "Indore"),
    ("Central Chronicle", "English", "Regional Daily", "Bhopal"),

    # --- spelling-variation cluster -----------------------------------------
    ("Express News", "English", "City Daily", "Noida"),
    ("Indian Xpress Weekly", "English", "Weekly", "Surat"),
    ("The Indus Express", "English", "National Daily", "Delhi"),
    ("Express Daily", "English", "City Daily", "Kanpur"),
    ("Star Express", "English", "City Daily", "Ludhiana"),

    # --- phonetic-variation cluster ------------------------------------------
    ("Foniks Times", "English", "Weekly", "Rajkot"),
    ("Nite Owl News", "English", "Evening Daily", "Mumbai"),
    ("Knight Rider Weekly", "English", "Entertainment", "Mumbai"),
    ("Kwik Kurrent", "English", "City Daily", "Thane"),
    ("Sound Check", "English", "Music", "Pune"),

    # --- Hindi (romanised) ----------------------------------------------------
    ("Dainik Jagran Bhaskar", "Hindi", "National Daily", "Kanpur"),
    ("Prabhat Khabar Express", "Hindi", "Regional Daily", "Ranchi"),
    ("Rashtriya Sahara Times", "Hindi", "National Daily", "Delhi"),
    ("Aaj Samay", "Hindi", "National Daily", "Delhi"),
    ("Navbharat Times Daily", "Hindi", "National Daily", "Mumbai"),
    ("Hindustan Dainik", "Hindi", "National Daily", "Patna"),
    ("Amar Ujala Prabhat", "Hindi", "Regional Daily", "Meerut"),
    ("Jan Satta", "Hindi", "National Daily", "Delhi"),
    ("Rajasthan Patrika Daily", "Hindi", "Regional Daily", "Jaipur"),
    ("Deshbandhu Times", "Hindi", "Regional Daily", "Raipur"),
    ("Sandhya Prakash", "Hindi", "Evening Daily", "Varanasi"),
    ("Pratidin Samachar", "Hindi", "Morning Daily", "Gwalior"),
    ("Sandhya Times", "Hindi", "Evening Daily", "Delhi"),
    ("Dainik Sandhya", "Hindi", "Evening Daily", "Ujjain"),
    ("Bharat Darpan", "Hindi", "National Daily", "Delhi"),
    ("Lokmat Samachar", "Hindi", "Regional Daily", "Jabalpur"),
    ("Kisan Varta", "Hindi", "Agriculture", "Hissar"),
    ("Mahila Jagran", "Hindi", "Lifestyle", "Lucknow"),
    ("Yuva Shakti Times", "Hindi", "Youth", "Bhopal"),
    ("Vyapar Sandesh", "Hindi", "Business", "Indore"),
    ("Swasthya Varta", "Hindi", "Health", "Varanasi"),
    ("Shiksha Prabhat", "Hindi", "Education", "Prayagraj"),
    ("Khel Samay", "Hindi", "Sports", "Delhi"),
    ("Mausam Varta", "Hindi", "Environment", "Shimla"),
    ("Jal Jyoti", "Hindi", "Environment", "Haridwar"),
    ("Satya Sandesh", "Hindi", "National Daily", "Delhi"),
    ("Vishwas Patrika", "Hindi", "National Daily", "Bhopal"),
    ("Shakti Times", "Hindi", "Regional Daily", "Nagpur"),
    ("Neta Ji Times", "Hindi", "Politics", "Lucknow"),
    ("Aaj Ki Raat", "Hindi", "Evening Daily", "Mumbai"),
    ("Usha Kaal", "Hindi", "Morning Daily", "Nasik"),
    ("Chandra Lok", "Hindi", "Weekly", "Bikaner"),
    ("Surya Prabhat", "Hindi", "Morning Daily", "Gaya"),
    ("Tara Samachar", "Hindi", "Evening Daily", "Shimla"),
    ("Dainik Tara", "Hindi", "Morning Daily", "Bhopal"),
    ("Roz Khabar", "Hindi", "Morning Daily", "Agra"),

    # --- Hindi (Devanagari) ---------------------------------------------------
    ("दैनिक संध्या", "Hindi", "Evening Daily", "Delhi"),
    ("प्रतिदिन समाचार", "Hindi", "Morning Daily", "Jaipur"),
    ("सुप्रभात भारत", "Hindi", "Morning Daily", "Varanasi"),
    ("नमस्कार देश", "Hindi", "Morning Daily", "Delhi"),
    ("संध्या समाचार", "Hindi", "Evening Daily", "Indore"),
    ("भारत वाणी", "Hindi", "National Daily", "Delhi"),
    ("जन की आवाज़", "Hindi", "Regional Daily", "Patna"),
    ("देश का दर्पण", "Hindi", "National Daily", "Lucknow"),
    ("किसान की बात", "Hindi", "Agriculture", "Hissar"),
    ("शिक्षा ज्योति", "Hindi", "Education", "Bhopal"),
    ("खेल जगत समाचार", "Hindi", "Sports", "Delhi"),
    ("स्वास्थ्य संदेश", "Hindi", "Health", "Jaipur"),
    ("व्यापार विश्व", "Hindi", "Business", "Surat"),
    ("महिला वाणी", "Hindi", "Lifestyle", "Lucknow"),
    ("युवा ज्योति", "Hindi", "Youth", "Kanpur"),

    # --- Marathi ---------------------------------------------------------------
    ("Maharashtra Times Daily", "Marathi", "Regional Daily", "Mumbai"),
    ("Lokmat Sandhya", "Marathi", "Evening Daily", "Nagpur"),
    ("Sakal Prabhat", "Marathi", "Morning Daily", "Pune"),
    ("Tarun Bharat Daily", "Marathi", "Regional Daily", "Kolhapur"),
    ("Pudhari Express", "Marathi", "Regional Daily", "Sangli"),
    ("Saamna Sandhya", "Marathi", "Evening Daily", "Mumbai"),
    ("Kesari Varta", "Marathi", "Regional Daily", "Pune"),
    ("Shetkari Batmi", "Marathi", "Agriculture", "Nashik"),
    ("Mahanagar Times", "Marathi", "City Daily", "Mumbai"),
    ("Krida Varta", "Marathi", "Sports", "Pune"),
    ("Arogya Deep", "Marathi", "Health", "Nagpur"),
    ("Vidya Prakash", "Marathi", "Education", "Kolhapur"),
    ("महाराष्ट्र संध्या", "Marathi", "Evening Daily", "Pune"),
    ("सकाळ प्रभात", "Marathi", "Morning Daily", "Pune"),
    ("तरुण भारत", "Marathi", "Regional Daily", "Belgaum"),
    ("शेतकरी वार्ता", "Marathi", "Agriculture", "Solapur"),

    # --- Gujarati ---------------------------------------------------------------
    ("Sandesh Daily", "Gujarati", "Regional Daily", "Ahmedabad"),
    ("Divya Bhaskar Express", "Gujarati", "Regional Daily", "Surat"),
    ("Gujarat Samachar Daily", "Gujarati", "Regional Daily", "Rajkot"),
    ("Janmabhoomi Pravasi", "Gujarati", "Regional Daily", "Bhavnagar"),
    ("Saurashtra Times", "Gujarati", "Regional Daily", "Rajkot"),
    ("Kutch Mitra Daily", "Gujarati", "Regional Daily", "Bhuj"),
    ("ગુજરાત સંદેશ", "Gujarati", "Regional Daily", "Ahmedabad"),
    ("દિવ્ય સંધ્યા", "Gujarati", "Evening Daily", "Surat"),

    # --- semantic-variation cluster (meaning overlaps) --------------------------
    ("Evening News Daily", "English", "Evening Daily", "Mumbai"),
    ("Nightly Herald", "English", "Evening Daily", "Kolkata"),
    ("Morning Sun", "English", "Morning Daily", "Chennai"),
    ("Daily Sunrise", "English", "Morning Daily", "Visakhapatnam"),
    ("The Evening Star", "English", "Evening Daily", "Pune"),
    ("Star of India", "English", "National Daily", "Mumbai"),
    ("Voice of Bharat", "English", "National Daily", "Delhi"),
    ("Mirror of India", "English", "National Daily", "Mumbai"),
    ("India News Chronicle", "English", "National Daily", "Delhi"),
    ("Bharat News Network", "English", "National Daily", "Noida"),
    ("The Daily World", "English", "National Daily", "Mumbai"),
    ("World Times India", "English", "National Daily", "Delhi"),
    ("Youth Voice Weekly", "English", "Youth", "Pune"),
    ("Farmers Chronicle", "English", "Agriculture", "Ludhiana"),
    ("Business World", "English", "Business", "Mumbai"),
    ("Education Herald", "English", "Education", "Chennai"),
    ("Health Post", "English", "Health", "Hyderabad"),
    ("Sports Star Weekly", "English", "Sports", "Bengaluru"),
    ("Cinema Express", "English", "Entertainment", "Chennai"),
    ("The Morning Voice", "English", "Morning Daily", "Kochi"),
    ("Today Times", "English", "National Daily", "Delhi"),
    ("Today's India", "English", "National Daily", "Mumbai"),

    # --- near-duplicate / prefix-suffix clusters --------------------------------
    ("New Indian Express", "English", "National Daily", "Chennai"),
    ("Indian Express Weekly", "English", "Weekly", "Mumbai"),
    ("The Daily Star Plus", "English", "Weekly", "Guwahati"),
    ("Star Daily", "English", "City Daily", "Madurai"),
    ("Express Herald", "English", "City Daily", "Kanpur"),
    ("Herald Express", "English", "City Daily", "Mangaluru"),
    ("The Phoenix Times", "English", "Weekly", "Pune"),
    ("Phoenix Weekly", "English", "Weekly", "Bengaluru"),
    ("Daily Mirror Express", "English", "City Daily", "Pune"),

    # --- unrelated / unique titles ----------------------------------------------
    ("Quantum Agriculture Weekly", "English", "Agriculture", "Pantnagar"),
    ("Blue River Gazette", "English", "City Daily", "Shillong"),
    ("Crimson Finch Journal", "English", "Literary", "Shantiniketan"),
    ("Amber Valley Post", "English", "Regional Daily", "Munnar"),
    ("Silent Peak Review", "English", "Literary", "Gangtok"),
    ("Orchid Lane Times", "English", "Lifestyle", "Puducherry"),
    ("Zephyr Sailing News", "English", "Sports", "Kochi"),
    ("Mango Grove Herald", "English", "Lifestyle", "Ratnagiri"),
    ("Coral Reef Chronicle", "English", "Environment", "Lakshadweep"),
    ("Monsoon Ragas", "English", "Music", "Pune"),
    ("Terracotta Times", "English", "Art", "Kolkata"),
    ("Juniper Journal", "English", "Botany", "Dehradun"),
    ("Falcon Flight Weekly", "English", "Adventure", "Manali"),
    ("Lantern Light Post", "English", "Literary", "Varanasi"),
    ("Saffron Harvest News", "English", "Agriculture", "Pampore"),
    ("Willow Creek Voice", "English", "Community", "Coonoor"),
]
